export * from './Hero'
export * from './About'
export * from './Services'
export * from './Partners'
// export * from './Testimonials'
export * from './WhyUs'
export * from './Work'
export * from './Blog'
export * from './YourChoice'
export * from './related-services'
export * from './faqs'
export * from './stats'
export * from './teams'