import { Inter } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/ui/custom/Cursor/custom-cursor";
import Navbar from '@/components/Header/navbar'

// SCSS GLOBAL
import '@/app/styles/globals.scss'
import { Footer } from "@/components/Footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
      </head>
      <body className={`${inter.className} `}>
        <div className="h-full overflow-x-hidden">
          <Navbar />
          {children}
          <Footer />
          <CustomCursor />
          <Toaster />
        </div>
      </body>
    </html>
  );
}
